name: KristjanKnigge
favicon: null
layout_spectrum: 0.24794
typography_spectrum: 0.64112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f69f06'
    - '#e95f0e'
    - '#ffffff'
    - '#ffff00'
    - '#ff0000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
